
services:
  db:
    image: mysql:latest  #Imagem oficial do MySQL
    container_name: mysql-container
    restart: always      # Reinicia o container em caso de falha
    environment:
      MYSQL_ROOT_PASSWORD: root@root  # Senha do usuário root
      MYSQL_DATABASE: kat_personalizados  # Nome do banco de dados
    ports:
      - "3306:3306"     # Mapeia a porta do container para a porta local
